spring:
  datasource:
    url: jdbc:sqlserver://sqlserverbannisters.database.windows.net:1433;database=CloudathonDemoDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: bannisters
    password: B@nnisters
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8191